### ISSUE TITLE
Utilities::readFromCSVFile the last key has a trailing \n

### ISSUE THREAD

**Issue by ahnt** [ahnt/MABE#25]
This function returns a map of vectors, and the keys are strings of their respective column headers. However, the key from the last column name has a trailing \n after it

Cheers Arend

**Comment by ahnt** [comment]
actually, it is not \n  but \r ... here is the fix:
				for (string key : dataLine) {
                    if(key.find('\r')!=string::npos){
                        key.erase(remove(key.begin(), key.end(), '\r'), key.end());
                    }
                    lookUpTable.push_back(key);  // add the key so we can make sure we assign the right values to the right columns
					data[key] = {};  // add an empty vector for each key into the map data
				}

**Comment by cliff-bohm** [comment]
fixed in parseCSVLine
